###############################################################################
## EMHASS CONFIG by Johan71
###############################################################################
## Do not remove; consider potential consequences.
sensor:
  - platform: template
    sensors:
      power_load_no_var_loads:
        friendly_name: "Power load no var loads"
        unit_of_measurement: "W"
        device_class: "power"
        unique_id: f8c3d9b2-7a4e-42d6-b9e1-3c8f1e5d67a1
        value_template: >
          {% set powerload = states('sensor.house_consumption_power') | float(0) %}
          {% set laddbox_power = states('sensor.go_echarger_265216_nrg_12') | float(0) %}
          {{ (powerload - laddbox_power) | round(1) }}
      ## Do not remove; consider potential consequences.
      pv_forecast_energy_per_hour:
        friendly_name: "PV Forecast Energy per Hour"
        unit_of_measurement: "kWh"
        device_class: energy
        value_template: >
          {% set forecasts = state_attr('sensor.p_pv_forecast', 'forecasts') %}
          {% if forecasts %}
            {% set now_hour = now().replace(minute=0, second=0, microsecond=0).strftime('%Y-%m-%d %H:00:00') %}
            {% set match = forecasts | selectattr('date', 'search', now_hour) | list %}
            {% if match %}
              {{ (match[0].p_pv_forecast | float / 1000) | round(2) }}
            {% else %}
              0
            {% endif %}
          {% else %}
            0
          {% endif %}

  ## Filter for fifobuffer
  - platform: filter
    name: "1_minute_average"
    entity_id: sensor.power_load_no_var_loads
    filters:
      - filter: time_simple_moving_average
        window_size: "00:01"
        precision: 0

  - platform: filter
    name: "15_minute_average"
    entity_id: sensor.1_minute_average
    filters:
      - filter: time_simple_moving_average
        window_size: "00:15"
        precision: 0

  - platform: filter
    name: "30_minute_average"
    entity_id: sensor.1_minute_average
    filters:
      - filter: time_simple_moving_average
        window_size: "00:30"
        precision: 0

  ## Load Forecast
  - platform: template
    sensors:
      load_forecast_kw:
        friendly_name: "Load Forecast (kW)"
        unit_of_measurement: "kW"
        value_template: >
          {{ (states('sensor.p_load_forecast') | float(0) / 1000) }}

input_number:
  weight_battery_discharge:
    name: "weight battery discharge"
    min: 0
    max: 5
    step: 0.01
    unit_of_measurement: "kr"
    mode: box
    icon: mdi:currency-usd

  weight_battery_charge:
    name: "weight battery charge"
    min: 0
    max: 5
    step: 0.01
    unit_of_measurement: "kr"
    mode: box
    icon: mdi:currency-usd

  # Ny rest_command till att träna PV-prognosmodellen
  emhass_historic_pv_days:
    name: EMHASS historic pv days
    min: 0
    max: 365
    step: 1
    mode: box

  # Ny input_number för PV Elevation Threshold
  emhass_pv_elevation_threshold:
    name: "EMHASS PV Elevation Threshold"
    min: 0
    max: 30
    step: 1
    mode: slider
    icon: mdi:solar-panel

  soc_final:
    name: soc_final
    min: 0
    max: 60
    step: 1
    unit_of_measurement: "%"
    mode: box
    icon: mdi:battery-charging

  ## Varius emhass sensor inputs
  emhass_battery_maximum_state_of_charge:
    name: "EMHASS Battery Maximum State of charge"
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    mode: box
    icon: mdi:battery

  emhass_battery_minimum_state_of_charge:
    name: "EMHASS Battery Minimum State of charge"
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    mode: box
    icon: mdi:battery

  emhass_soc_final:
    name: "EMHASS soc final"
    min: 0
    max: 50
    step: 1
    unit_of_measurement: "%"
    mode: slider

  emhass_alpha:
    name: "EMHASS alpha"
    min: 0
    max: 3
    step: 0.05
    mode: box
    icon: mdi:alpha

  emhass_beta:
    name: "EMHASS beta"
    min: 0
    max: 3
    step: 0.05
    mode: box
    icon: mdi:beta

  emhass_battery_charge_efficiency:
    name: "EMHASS Battery Charge Efficiency"
    min: 0.01
    max: 1.0
    step: 0.01
    unit_of_measurement: "%"
    mode: slider
    icon: mdi:battery

  emhass_battery_discharge_efficiency:
    name: "EMHASS Battery Discharge Efficiency"
    min: 0.01
    max: 1.0
    step: 0.01
    unit_of_measurement: "%"
    mode: slider
    icon: mdi:battery

input_boolean:
  automation_timetrigger:
    name: automation timetrigger
    icon: mdi:lock-pattern

  set_use_adjusted_pv:
    name: Set Use Adjusted PV
    icon: mdi:solar-power

  ## Emhass notify wwhen batterymode changes
  emhass_notify:
    name: EMHASS Notify
    icon: mdi:cellphone-arrow-down

## Automation input select
input_select:
  emhass_discharge_mode:
    name: "EMHASS Discharge Mode"
    options:
      - "Limited Power"
      - "Battery Power"
      - "5000 W"
      - "3500 W"
    icon: mdi:toggle-switch

  emhass_charge_mode:
    name: "EMHASS Charge Mode"
    options:
      - "Limited Power"
      - "Battery Power"
      - "5000 W"
      - "3500 W"
    icon: mdi:toggle-switch

  # Ny input_select för PV ML Modell (valfritt)
  emhass_pv_ml_model:
    name: "EMHASS PV ML Model"
    options:
      - "LassoRegression"
      - "LinearRegression"
      - "KNeighborsRegressor"
      - "RandomForestRegression"
      - "GradientBoostRegression"
      - "AdaBoostRegression"
    icon: mdi:brain

  # Input select för costfun
  emhass_costfun:
    name: EMHASS Costfun
    options:
      - profit
      - cost
      - self-consumption
    icon: mdi:chart-bubble

## Fifobuffer textfile
input_text:
  fi_fo_buffer:
    name: Fi fo buffer
    max: 256
################################################################################
##      END
################################################################################
